version: 0.2

phases:
  pre_build:
    commands:
      - echo "=== Pre-Build Phase ==="
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo "Repository: $REPOSITORY_URI"
      - echo "Tag: $IMAGE_TAG"
      - ls -la

  build:
    commands:
      - echo "=== Build Phase ==="
      - echo "Building Docker image at $(date)"
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG . || (docker build -t $REPOSITORY_URI:$IMAGE_TAG . 2>&1 | tail -50; exit 1)
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest
      - echo "Build successful at $(date)"

  post_build:
    commands:
      - echo "=== Post-Build Phase ==="
      - echo "Pushing Docker images at $(date)"
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - echo "Creating imagedefinitions.json..."
      - printf '[{"name":"wildrydes-app","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo "imagedefinitions.json created:"
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
  name: BuildArtifact

cache:
  paths:
    - /root/.npm/**/*
